model_list:
  - model_name: "claude-sonnet-4-20250514"
    litellm_params:
      model: openrouter/qwen/qwen3-coder
      api_base: https://openrouter.ai/api/v1
      max_tokens: 8192
  - model_name: "sonnet 4"
    litellm_params:
      model: openrouter/qwen/qwen3-coder
      api_base: https://openrouter.ai/api/v1
      max_tokens: 8192
  - model_name: "qwen coder"
    litellm_params:
      model: openrouter/qwen/qwen3-coder
      api_base: https://openrouter.ai/api/v1
      max_tokens: 8192

litellm_settings: {}

general_settings:
  disable_database: true
